
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Acer
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lblNumberA = new javax.swing.JLabel();
        lblNumberB = new javax.swing.JLabel();
        txtNumberA = new javax.swing.JTextField();
        txtNumberB = new javax.swing.JTextField();
        Round = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMutiple = new javax.swing.JButton();
        btnDevide = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtResult = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cacular Form");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parameters", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblNumberA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberA.setText("Number A:");

        lblNumberB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumberB.setText("Number B:");

        txtNumberA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumberA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberAActionPerformed(evt);
            }
        });

        txtNumberB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Round.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Round.setText("Round");
        Round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblNumberA))
                    .addComponent(lblNumberB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Round)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNumberA)
                    .addComponent(txtNumberB))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberA))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumberB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberB))
                .addGap(18, 18, 18)
                .addComponent(Round))
        );

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMinus.setText("Minus");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnMutiple.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMutiple.setText("Mutiple");
        btnMutiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutipleActionPerformed(evt);
            }
        });

        btnDevide.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDevide.setText("Devide");
        btnDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevideActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtResult.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        txtResult.setForeground(new java.awt.Color(255, 0, 0));
        txtResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnMutiple, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnMinus)
                    .addComponent(btnMutiple)
                    .addComponent(btnDevide))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumberAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberAActionPerformed

    }//GEN-LAST:event_txtNumberAActionPerformed

    private void RoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoundActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (!Check()) {
            JOptionPane.showMessageDialog(this, "Please enter a number!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.add();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if (!Check()) {
            JOptionPane.showMessageDialog(this, "Please enter a number!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.minus();
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMutipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutipleActionPerformed
        if (!Check()) {
            JOptionPane.showMessageDialog(this, "Please enter a number!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.multiple();
        }
    }//GEN-LAST:event_btnMutipleActionPerformed

    private void btnDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevideActionPerformed
        if (!Check()) {
            JOptionPane.showMessageDialog(this, "Please enter a number!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.divide();
        }
    }//GEN-LAST:event_btnDevideActionPerformed
    //Check user input
    private boolean Check() {
        if (!txtNumberA.getText().matches("[-]\\d+")
                && !txtNumberA.getText().matches("\\d+")
                && !txtNumberA.getText().matches("[-]\\d+[.]\\d+")
                && !txtNumberA.getText().matches("\\d+[.]\\d+")) {
            return false;
        } else if (!txtNumberB.getText().matches("[-]\\d+")
                && !txtNumberB.getText().matches("\\d+")
                && !txtNumberB.getText().matches("[-]\\d+[.]\\d+")
                && !txtNumberB.getText().matches("\\d+[.]\\d+")) {
            return false;
        }
        return true;
    }

    private float round(float number) {
        return Math.round(number);
    }

    /**
     * add two number
     *
     * @return result
     */
    private float add() {
        float add = Float.parseFloat(txtNumberA.getText()) + Float.parseFloat(txtNumberB.getText());
        boolean isRound = Round.isSelected();
        add = isRound ? round(add) : add;
        txtResult.setText(String.valueOf(add));
        return add;
    }

    /**
     * sub two number
     *
     * @return result
     */
    private float minus() {
        float minus = Float.parseFloat(txtNumberA.getText()) - Float.parseFloat(txtNumberB.getText());
        boolean isRound = Round.isSelected();
        minus = isRound ? round(minus) : minus;
        txtResult.setText(String.valueOf(minus));
        return minus;
    }

    /**
     * multiple two number
     *
     * @return result
     */
    private float multiple() {
        float multiple = Float.parseFloat(txtNumberA.getText()) * Float.parseFloat(txtNumberB.getText());
        boolean isRound = Round.isSelected();
        multiple = isRound ? round(multiple) : multiple;
        txtResult.setText(String.valueOf(multiple));
        return multiple;
    }

    /**
     * divide two number
     * @return result
     */
    private float divide() {
        float divide = Float.parseFloat(txtNumberA.getText()) / Float.parseFloat(txtNumberB.getText());
        boolean isRound = Round.isSelected();
        divide = isRound ? round(divide) : divide;
        txtResult.setText(String.valueOf(divide));
        return divide;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Round;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDevide;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMutiple;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNumberA;
    private javax.swing.JLabel lblNumberB;
    private javax.swing.JTextField txtNumberA;
    private javax.swing.JTextField txtNumberB;
    private javax.swing.JLabel txtResult;
    // End of variables declaration//GEN-END:variables
}
