
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Ex01_DemoColor extends javax.swing.JFrame {

    /**
     * Creates new form Ex01_DemoColor
     */
    public Ex01_DemoColor() {
        initComponents();
        SetColor();
    }
    
    void SetColor() {
        //Create color
        Color color = new Color(sdRed.getValue(), sdGreen.getValue(), sdBlue.getValue());
        //Create color contrast
        Color colorContrast = new Color(255 - sdRed.getValue(), 
                                        255 - sdGreen.getValue(), 
                                        255 - sdBlue.getValue());
        txtColorDemo.setBackground(color);
        txtColorDemo.setForeground(colorContrast);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sdRed = new javax.swing.JSlider();
        txtColorDemo = new javax.swing.JTextField();
        sdBlue = new javax.swing.JSlider();
        sdGreen = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Color Mixer");

        sdRed.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sdRed.setMajorTickSpacing(50);
        sdRed.setMaximum(255);
        sdRed.setMinorTickSpacing(25);
        sdRed.setOrientation(javax.swing.JSlider.VERTICAL);
        sdRed.setPaintLabels(true);
        sdRed.setPaintTicks(true);
        sdRed.setToolTipText("");
        sdRed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sdRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdRedStateChanged(evt);
            }
        });

        txtColorDemo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtColorDemo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColorDemo.setText("This is demo text");

        sdBlue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sdBlue.setMajorTickSpacing(50);
        sdBlue.setMaximum(255);
        sdBlue.setMinorTickSpacing(25);
        sdBlue.setOrientation(javax.swing.JSlider.VERTICAL);
        sdBlue.setPaintLabels(true);
        sdBlue.setPaintTicks(true);
        sdBlue.setToolTipText("");
        sdBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdBlueStateChanged(evt);
            }
        });

        sdGreen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sdGreen.setMajorTickSpacing(50);
        sdGreen.setMaximum(255);
        sdGreen.setMinorTickSpacing(25);
        sdGreen.setOrientation(javax.swing.JSlider.VERTICAL);
        sdGreen.setPaintLabels(true);
        sdGreen.setPaintTicks(true);
        sdGreen.setToolTipText("");
        sdGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdGreenStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Red");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Green");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Blue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtColorDemo)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sdRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sdGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sdBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtColorDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdRed, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sdRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdRedStateChanged
        SetColor();
    }//GEN-LAST:event_sdRedStateChanged

    private void sdGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdGreenStateChanged
        SetColor();
    }//GEN-LAST:event_sdGreenStateChanged

    private void sdBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdBlueStateChanged
        SetColor();
    }//GEN-LAST:event_sdBlueStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex01_DemoColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex01_DemoColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex01_DemoColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex01_DemoColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex01_DemoColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSlider sdBlue;
    private javax.swing.JSlider sdGreen;
    private javax.swing.JSlider sdRed;
    private javax.swing.JTextField txtColorDemo;
    // End of variables declaration//GEN-END:variables
}
